"""Render this analysis's note from its generated tables."""

from __future__ import annotations

import textwrap
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
TAB = HERE / "out/tab"
FIG = "out/fig"


def reflow(md: str, width: int = 80) -> str:
    out = []
    for block in md.split("\n\n"):
        st = block.strip()
        if not st or st[0] in "#|!>" or "\n|" in block:
            out.append(block)
        elif st.startswith("- "):
            items, cur = [], []
            for line in block.split("\n"):
                if line.startswith("- ") and cur:
                    items.append(" ".join(cur))
                    cur = [line]
                else:
                    cur.append(line)
            items.append(" ".join(cur))
            out.append(
                "\n".join(
                    textwrap.fill(
                        " ".join(i[2:].split()),
                        width,
                        initial_indent="  ",
                        subsequent_indent="  ",
                        break_on_hyphens=False,
                    ).replace("  ", "- ", 1)
                    for i in items
                )
            )
        else:
            out.append(
                textwrap.fill(
                    " ".join(block.split()),
                    width,
                    break_on_hyphens=False,
                    break_long_words=False,
                )
            )
    return "\n\n".join(out) + "\n"


def main() -> None:
    caste = pd.read_csv(TAB / "by_caste.csv")
    sc = caste[caste.caste == "Scheduled Caste"].iloc[0]
    other = caste[caste.caste == "neither"].iloc[0]
    st = caste[caste.caste == "Scheduled Tribe"].iloc[0]
    overall = float((caste["share_of_people"] * caste["wrong_per_100"]).sum())
    resolution = (
        pd.read_csv(TAB / "surname_resolution.csv").set_index("state")
        if (TAB / "surname_resolution.csv").exists()
        else None
    )

    def _share(state: str, col: str = "analytic_share") -> str:
        """Rendered coverage, or "not available" when the state was skipped."""
        if resolution is None or state not in resolution.index:
            return "not available"
        return f"{100 * float(resolution.loc[state, col]):.0f}%"

    bihar_share = _share("bihar")
    maharashtra_share = _share("maharashtra")
    rajasthan_share = _share("rajasthan")
    maharashtra_gendered = _share("maharashtra", "gendered_share")
    maharashtra_resolved = _share("maharashtra", "resolved_share")
    blind_overall = float(
        (caste["share_of_people"] * caste["blind_wrong_per_100"]).sum()
    )
    other_gain = other.blind_wrong_per_100 - other.wrong_per_100

    caste_rows = "\n".join(
        f"| {r.caste} | {r.share_of_people:.0%} | "
        f"{r.blind_wrong_per_100:.0f} | {r.wrong_per_100:.0f} | "
        f"{r.name_vagueness_per_100:.0f} |"
        for r in caste.itertuples()
    )
    sex_rows = ""
    sex_conclusion = "No supported state-level sex comparison was available."
    if (TAB / "sex_gap.csv").exists():
        g = pd.read_csv(TAB / "sex_gap.csv").sort_values("gap", ascending=False)
        sex_rows = "\n".join(
            f"| {r.state.replace('_', ' ').title()} | {r.men:.0f} | {r.women:.0f} "
            f"| {r.gap:+.1f} |"
            for r in g.itertuples()
        )
        if not g.empty:
            higher = g.iloc[0]
            lower = g.iloc[-1]
            sex_conclusion = (
                f"Women are worse off in {higher.state.replace('_', ' ').title()} "
                f"by {abs(higher.gap):.1f} mistakes per hundred and better off in "
                f"{lower.state.replace('_', ' ').title()} by {abs(lower.gap):.1f}. "
                "The direction reverses."
            )

    md = f"""# Whose name tells you nothing

### The errors are not spread evenly, and the direction matters

*Every number here is generated by `pipeline.py`; the tables are in `out/tab`.*

The other analyses in this repo report an average: a surname saves about ten
mistakes per hundred, and for most people it changes nothing at all. An average
hides who. If the uninformative names are not spread evenly across people, then
every name-based caste method has a differential error rate in a knowable
direction, and anyone using one ought to know which way it runs.

It is not spread evenly.

## The guess is wrong about two thirds of Dalits and four percent of everyone else

Score the same guess separately on each group. Knowing nothing, the best you can
do is name the largest group and say it every time, which is right about all of
that group and wrong about everyone else. Then let the name in.

| your caste | share of India | wrong knowing nothing | wrong with the name | vagueness of the names you carry |
|---|---|---|---|---|
{caste_rows}

![What the guess gets wrong, by the person's own caste]({FIG}/by_caste.png)

The guess is wrong about **{sc.wrong_per_100:.0f} of every 100 Dalits** and
**{other.wrong_per_100:.0f} of every 100 people outside the schedules**. That is
a {sc.wrong_per_100 / other.wrong_per_100:.0f}-fold gap, and it is the number to
carry away. Weight the two middle columns by the shares beside them and they
come to {blind_overall:.0f} and {overall:.0f}, the mistakes per hundred a blind
guess and a name-based guess make across everybody. This is one estimator split
by who it is applied to, not a new one.

Note what the table does **not** say. The name is not useless for Dalits: it
takes them from wrong about all of them to wrong about {sc.wrong_per_100:.0f} in
a hundred. It does more for Adivasis, {st.blind_wrong_per_100:.0f} down to
{st.wrong_per_100:.0f}. It does nothing for people outside the schedules and in
fact costs them {-other_gain:.0f} per hundred, because knowing nothing already
had them right. The trouble is that a large gain still leaves Dalits far and
away the worst served.

The last column is a different quantity and is kept because it is the one the
mistake is easy to make with. It is how vague the names a group carries are --
one minus the largest share in the name's own composition, averaged over that
group's bearers. It is a property of names, not of people, so it cannot be read
as how often the guess is wrong about someone.

So the method is not weakly accurate across the board. It is accurate about the
advantaged and poor about the disadvantaged, which is the opposite of what a
user assuming uniform error would expect, and it runs in the direction that
makes a naive audit understate discrimination against exactly the group the
audit is for: two thirds of the Dalits in the data land in the comparison
group, on both sides of the gap being measured.

## By sex, there is no consistent story

The obvious next guess is that women fare worse, since a woman in the Hindi belt
is often recorded under a name that marks her sex rather than her family. That
was my prediction. It does not hold.

| state | mistakes on men | on women | gap |
|---|---|---|---|
{sex_rows}

![Mistakes by sex]({FIG}/by_sex.png)

{sex_conclusion} A sex-marking name is not
automatically a worse-predicted one: Devi puts you at the base rate, and plenty
of the names men carry in these states — Ram, Das, Lal — are worse than the base
rate. Reported here because it was the prediction going in.

## What this means for anyone using a name-based method

The caste result is the one to carry away, and it is not a caveat. Any method
that infers caste from an Indian surname — this repo's, outkast's, a
BISG-style transfer — will **miss most Scheduled Caste individuals while
classifying nearly everyone else correctly**. An audit that assumes uniform
error understates the error made on Dalits by about
{sc.wrong_per_100 - other.wrong_per_100:.0f} mistakes per hundred.

## Limits

- **SC / ST / Other only**, since that is what the census extract has. The
  OBC and forward line is invisible, and the differential could look different
  across it.
- **The caste split is computed from the same table it evaluates.** It is a
  decomposition of a known distribution, not an out-of-sample test, so it
  describes the ceiling a perfect user of this table would hit rather than the
  performance of any fitted model.
- **The sex split covers only Bihar, Rajasthan, and Maharashtra**, the states
  supported by Upnaam's `resolver-v1` and present locally. It uses Upnaam's
  recorded surname, not a resolved family surname.
- **The sex split needs a given name naampy can gender, and a surname the caste
  table knows.** After both, the estimates rest on {bihar_share} of the Bihar
  roll, {maharashtra_share} of the Maharashtra roll and {rajasthan_share} of the
  Rajasthan roll. Each earlier step looks healthier: Maharashtra resolves a
  surname for {maharashtra_resolved} of its roll and genders one for
  {maharashtra_gendered}, but a surname that is gendered and then has no caste
  row never reaches the estimate. Bihar is the only one of the three built on
  most of a state.
- **Nothing here is per-name.** The tables report groups, never a ranked list of
  which names give which people away.

---

*Caste composition from [outkast](https://github.com/appeler/outkast)'s SECC
2011 extract, the same source as analysis 01. Sex from
[naampy](https://github.com/appeler/naampy)'s first-name counts applied to
[Upnaam](https://github.com/in-rolls/upnaam)'s `resolver-v1` aggregate roll
outputs.*
"""
    out = HERE / "note.md"
    out.write_text(reflow(md))
    print(f"wrote {out} ({len(out.read_text().splitlines())} lines)")


if __name__ == "__main__":
    main()
