"""Render this analysis's note from its generated tables."""

from __future__ import annotations

import json
import textwrap
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
TAB = HERE / "out/tab"
FIG = "out/fig"


def reflow(md: str, width: int = 80) -> str:
    out = []
    for block in md.split("\n\n"):
        st = block.strip()
        if not st or st[0] in "#|!>" or "\n|" in block:
            out.append(block)
        elif st.startswith("- "):
            items, cur = [], []
            for line in block.split("\n"):
                if line.startswith("- ") and cur:
                    items.append(" ".join(cur))
                    cur = [line]
                else:
                    cur.append(line)
            items.append(" ".join(cur))
            out.append(
                "\n".join(
                    textwrap.fill(
                        " ".join(i[2:].split()),
                        width,
                        initial_indent="  ",
                        subsequent_indent="  ",
                        break_on_hyphens=False,
                    ).replace("  ", "- ", 1)
                    for i in items
                )
            )
        else:
            out.append(
                textwrap.fill(
                    " ".join(block.split()),
                    width,
                    break_on_hyphens=False,
                    break_long_words=False,
                )
            )
    return "\n\n".join(out) + "\n"


def main() -> None:
    s = json.loads((TAB / "summary.json").read_text())
    caste = pd.read_csv(TAB / "by_caste.csv")
    blind = s["blind_per_100"]
    sc = caste[caste.caste == "Scheduled Caste"].iloc[0]
    other = caste[caste.caste == "neither"].iloc[0]

    caste_rows = "\n".join(
        f"| {r.caste} | {r.share_of_people:.0%} | {r.mistakes_per_100:.0f} | "
        f"{r.found_by_the_guess:.0%} |"
        for r in caste.itertuples()
    )
    sex_rows = ""
    if (TAB / "sex_gap.csv").exists():
        g = pd.read_csv(TAB / "sex_gap.csv").sort_values("gap", ascending=False)
        sex_rows = "\n".join(
            f"| {r.state.replace('_', ' ').title()} | {r.men:.0f} | {r.women:.0f} "
            f"| {r.gap:+.1f} |"
            for r in g.itertuples()
        )

    md = f"""# Whose name tells you nothing

### The errors are not spread evenly, and the direction matters

*Every number here is generated by `pipeline.py`; the tables are in `out/tab`.*

The other analyses in this repo report an average: a surname saves about ten
mistakes per hundred, and for most people it changes nothing at all. An average
hides who. If the uninformative names are not spread evenly across people, then
every name-based caste method has a differential error rate in a knowable
direction, and anyone using one ought to know which way it runs.

It is not spread evenly.

## A guess from the name does nothing for Dalits

Knowing nothing at all about someone, the best guess is wrong
{blind:.0f} times in a hundred. Now weight each surname not by everybody who
carries it, but by the people **of one caste** who carry it. That gives what a
member of that caste actually experiences.

| your caste | share of India | mistakes made on you | the guess finds you |
|---|---|---|---|
{caste_rows}

![Mistakes by the carrier's own caste]({FIG}/by_caste.png)

A Dalit is guessed wrong **{sc.mistakes_per_100:.0f} times in a hundred**,
against {blind:.0f} for knowing nothing whatever. The name has bought
essentially nothing. For everyone outside the schedules it buys a great deal:
{other.mistakes_per_100:.0f} mistakes instead of {blind:.0f}.

The recall column says the same thing from the other side. The guessing finds
{sc.found_by_the_guess:.0%} of Dalits and {other.found_by_the_guess:.0%} of
everyone else.

So the method is not weakly accurate across the board. It is accurate about the
advantaged and blind about the disadvantaged, which is the opposite of what a
user assuming uniform error would expect, and it runs in the direction that
makes a naive audit understate discrimination against exactly the group the
audit is for.

## By sex, there is no consistent story

The obvious next guess is that women fare worse, since a woman in the Hindi belt
is often recorded under a name that marks her sex rather than her family. That
was my prediction. It does not hold.

| state | mistakes on men | on women | gap |
|---|---|---|---|
{sex_rows}

![Mistakes by sex]({FIG}/by_sex.png)

Women are worse off in Bihar by three mistakes per hundred and **better** off in
Uttar Pradesh by two. The direction reverses. A sex-marking name is not
automatically a worse-predicted one: Devi puts you at the base rate, and plenty
of the names men carry in these states — Ram, Das, Lal — are worse than the base
rate. Reported here because it was the prediction going in.

## What this means for anyone using a name-based method

The caste result is the one to carry away, and it is not a caveat. Any method
that infers caste from an Indian surname — this repo's, outkast's, a
BISG-style transfer — will be **roughly as good as chance for Scheduled Caste
individuals and substantially better than chance for everyone else**. An
audit that assumes uniform error will understate error for Dalits by about
{sc.mistakes_per_100 - other.mistakes_per_100:.0f} mistakes per hundred.

## Limits

- **SC / ST / Other only**, since that is what the census extract has. The
  OBC and forward line is invisible, and the differential could look different
  across it.
- **The caste split is computed from the same table it evaluates.** It is a
  decomposition of a known distribution, not an out-of-sample test, so it
  describes the ceiling a perfect user of this table would hit rather than the
  performance of any fitted model.
- **The sex split needs a first name naampy can gender**, which covers part of
  each roll, and it uses the surname as written rather than a resolved family
  name.
- **Nothing here is per-name.** The tables report groups, never a ranked list of
  which names give which people away.

---

*Caste composition from [outkast](https://github.com/appeler/outkast)'s SECC
2011 extract, the same source as analysis 01. Sex from
[naampy](https://github.com/appeler/naampy)'s first-name counts applied to
[instate](https://github.com/appeler/instate)'s raw rolls.*
"""
    out = HERE / "note.md"
    out.write_text(reflow(md))
    print(f"wrote {out} ({len(out.read_text().splitlines())} lines)")


if __name__ == "__main__":
    main()
