"""Render this analysis's note from its generated tables."""

from __future__ import annotations

import json
import textwrap
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
TAB = HERE / "out/tab"
FIG = "out/fig"


def reflow(md: str, width: int = 80) -> str:
    def fill(text: str, indent: str = "") -> str:
        return textwrap.fill(
            " ".join(text.split()),
            width=width,
            initial_indent=indent,
            subsequent_indent=indent,
            break_on_hyphens=False,
            break_long_words=False,
        )

    out = []
    for block in md.split("\n\n"):
        stripped = block.strip()
        if not stripped or stripped[0] in "#|!>" or "\n|" in block:
            out.append(block)
        elif stripped.startswith("- "):
            items, current = [], []
            for line in block.split("\n"):
                if line.startswith("- ") and current:
                    items.append(" ".join(current))
                    current = [line]
                else:
                    current.append(line)
            items.append(" ".join(current))
            out.append(
                "\n".join(fill(i[2:], "  ").replace("  ", "- ", 1) for i in items)
            )
        else:
            out.append(fill(block))
    return "\n\n".join(out) + "\n"


def main() -> None:
    t = pd.read_csv(TAB / "ladders.csv")
    mh = t[t.ladder == "mahadalit_raw"].set_index("level") if "ladder" in t else None
    s = json.loads((TAB / "summary.json").read_text())

    def cell(target, level, col="mistakes_per_100"):
        row = t[
            (t["ladder"] == "records") & (t["target"] == target) & (t["level"] == level)
        ]
        return float(row[col].iloc[0])

    def m(target, level):
        return round(cell(target, level))

    base_j = round(s["baselines_mistakes_per_100"]["records/jati"])
    base_c = round(s["baselines_mistakes_per_100"]["records/category_religion"])
    rungs = ["surname+village", "surname+zone", "surname+district", "surname"]
    labels = [
        "surname + village",
        "surname + zone",
        "surname + district",
        "surname alone",
    ]
    rows = "\n".join(
        f"| {lab} | {m('jati', lv)} | {m('category_religion', lv)} |"
        for lab, lv in zip(labels, rungs)
    )
    loo_gap = max(
        abs(cell(tg, lv, "mistakes_per_100_loo") - cell(tg, lv))
        for tg in ("jati", "category_religion")
        for lv in rungs
    )

    mahadalit_households = s.get("mahadalit", {}).get("households", 0)
    mahadalit_jatis = s.get("mahadalit", {}).get("jatis", 0)
    if mh is not None and len(mh):
        hamlet_tola = mh.loc["surname+tola", "mistakes_per_100_loo"]
        hamlet_tola_plug = mh.loc["surname+tola", "mistakes_per_100"]
        hamlet_village = mh.loc["surname+village", "mistakes_per_100_loo"]
        hamlet_surname = mh.loc["surname", "mistakes_per_100_loo"]
        hamlet_place = mh.loc["tola alone", "mistakes_per_100_loo"]

    md = f"""# Jati is a local fact

### How fast does caste information die as the place gets bigger?

*Every number here is generated by `pipeline.py`; the tables are in `out/tab`.*

The other analysis in this repo asks what a surname alone tells you about caste
across India, and finds: not much. This one asks the obvious follow-up. If a
surname alone is weak, is that because surnames are weak — or because we threw
away the place?

Bihar can answer it, because the land records let you put a name and a village
together. The measure is the same one used throughout: **of a hundred people,
how many would you get wrong** if you guessed the commonest group among people
you can place the same way.

## The answer

![How much a name tells you, by how closely you can place someone]({FIG}/atrophy.png)

| what you know about them | mistakes per 100, guessing **jati** | guessing **broad category** |
|---|---|---|
| nothing at all | {base_j} | {base_c} |
{rows}

Read the surname column upward. Knowing someone's surname and their village
leaves you wrong {m('jati', 'surname+village')} times in a hundred about which
of {s['groups']['jati']} jatis they belong to. Keep the surname, throw away the
village, and you are wrong {m('jati', 'surname')} times. **Adding the village
cuts the mistakes you would otherwise make by about two-thirds.**

The atrophy is steep and it is orderly: {m('jati', 'surname+village')} in a
village, {m('jati', 'surname+zone')} across a zone,
{m('jati', 'surname+district')} across a district,
{m('jati', 'surname')} across the state.

## One rung below the village

The land records stop at the village. Bihar's Mahadalit census does not: it
records the **tola**, the hamlet, and hamlets in Bihar are frequently
caste-segregated to the point of being named for it — `chamar tola`,
`mushar tola`, `harijan tola`.

![The hamlet rung]({FIG}/hamlet_ladder.png)

Across {mahadalit_households:,} households and {mahadalit_jatis} Scheduled Caste
jatis, knowing a surname and a hamlet leaves you wrong
**{hamlet_tola:.0f} times in a hundred**, against {hamlet_village:.0f} at the
village and {hamlet_surname:.0f} for the surname alone. One level below the
village nearly halves the error again.

Half of those hamlet cells hold a single household, and a cell of one is
"predicted" perfectly by construction, so every figure here is leave-one-out:
each household is guessed from a cell that excludes it. That moves the hamlet
from {hamlet_tola_plug:.1f} to {hamlet_tola:.1f}, about one mistake in a
hundred, which is why the rung stands.

The hamlet is also doing work on its own. Knowing only which hamlet someone
lives in, with no name at all, leaves you wrong {hamlet_place:.0f} times —
better than knowing only their surname ({hamlet_surname:.0f}). The segregation is
that sharp. But the pair is far better than either piece, which is the same
lesson one level up.

These numbers are Scheduled Caste households only, so they are within-Dalit
across {mahadalit_jatis} jatis and are not comparable to the 141-jati land ladder
above.

## Neither the name nor the place, on its own

![Name against place]({FIG}/name_vs_place.png)

Knowing only where someone lives, with no name at all, leaves you wrong
{m('jati', 'village')} times in a hundred. Knowing only the name leaves you
wrong {m('jati', 'surname')}. Knowing both leaves you wrong
{m('jati', 'surname+village')}. The pair is worth far more than either piece,
which is the whole reason caste reads as legible to people who live somewhere
and illegible to people who move.

## One name, three distances

![A hundred Singhs]({FIG}/rung_waffles.png)

Singh is a good name to watch, because it is carried by jatis at opposite ends
of the hierarchy — Rajput and Bhumihar near the top, Ahir, Kurmi and Koeri well
below. In one village, 87 of a hundred Singhs are Ahir and you would be wrong 13
times. Widen to the district and the same name is spread across five jatis with
none holding half; you are wrong 56 times. Widening further to the whole state
barely changes it, at 57.

Devi is the opposite kind of name, and the same one that dominates the other
analysis: it is a gender marker, not a caste marker. Even inside a single
village it leaves you wrong about 51 times in a hundred.

## Broad categories atrophy too, from a lower base

Guessing the reservation category rather than the jati is much easier — five or
six groups instead of {s['groups']['jati']} — but it decays the same way:
{m('category_religion', 'surname+village')} mistakes with the village,
{m('category_religion', 'surname')} without it, against {base_c} knowing
nothing.

Splitting Muslims out of those categories changes almost nothing: the five-way
and six-way ladders sit within a point of each other at every rung. That is
itself worth noting — it means surnames already separate Muslim from non-Muslim
about as well as the category data can, so nothing was hiding in the residual.

## What could be wrong with this, and is not

Half the cells at village level hold a single jati, so the sharp village figure
could have been an artifact of tiny cells that are "predicted" perfectly by
construction. It is not. There are no single-person cells, and scoring every
person against a cell that excludes them moves no rung by more than
{loo_gap:.1f} of a mistake per hundred.

## What this does not cover

- **Bihar only.** The ladders are built from Bihar land records and a Bihar
  census. Nothing here generalises to states where jatis, surnames or
  settlement patterns differ.
- **Landowners only.** The records ladder counts land-owning accounts, so it
  is not a random slice of Bihar. It under-represents exactly the landless
  households that are disproportionately Dalit and EBC, and that selection
  runs in an unknown direction for these numbers.
- **The village is doing work you may not have.** The point of the finding is
  that the pair is strong. Nobody meeting a stranger in a city has the village,
  which is what the other analysis measures.

---

*Source: the `records_ladder` and `census_ladder` tables shipped in
[naampata](https://github.com/in-rolls/jati), built from Bihar land records
({s['records_accounts'] / 1e6:.1f}M land-owning accounts across
{s['groups']['jati']} jatis) and the Mahadalit census. The Muslim split uses the
caste dictionary in the [land](https://github.com/in-rolls/land) repo, which
carries a religion flag beside each caste's reservation category.*
"""
    out = HERE / "note.md"
    out.write_text(reflow(md))
    print(f"wrote {out} ({len(out.read_text().splitlines())} lines)")


if __name__ == "__main__":
    main()
