"""Render this analysis's note from its generated tables."""

from __future__ import annotations

import json
import textwrap
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
TAB = HERE / "out/tab"
FIG = "out/fig"


def reflow(md: str, width: int = 80) -> str:
    def fill(text: str, indent: str = "") -> str:
        return textwrap.fill(
            " ".join(text.split()),
            width=width,
            initial_indent=indent,
            subsequent_indent=indent,
            break_on_hyphens=False,
            break_long_words=False,
        )

    out = []
    for block in md.split("\n\n"):
        st = block.strip()
        if not st or st[0] in "#|!>" or "\n|" in block:
            out.append(block)
        elif st.startswith("- "):
            items, cur = [], []
            for line in block.split("\n"):
                if line.startswith("- ") and cur:
                    items.append(" ".join(cur))
                    cur = [line]
                else:
                    cur.append(line)
            items.append(" ".join(cur))
            out.append(
                "\n".join(fill(i[2:], "  ").replace("  ", "- ", 1) for i in items)
            )
        else:
            out.append(fill(block))
    return "\n\n".join(out) + "\n"


def main() -> None:
    s = json.loads((TAB / "summary.json").read_text())
    by_state = pd.read_csv(TAB / "by_state.csv")
    lv = s["levels"]
    v = s["variants"]
    cost = None
    if (TAB / "title_signal.csv").exists():
        cost = pd.read_csv(TAB / "title_signal.csv")

    def st(name, col):
        return by_state.loc[by_state.state == name, col].iloc[0]

    level_rows = "\n".join(
        f"| {lv[k]['label']} | {lv[k]['top_name_share']:.1%} | "
        f"{lv[k]['names_for_25']:,} | {lv[k]['names_for_50']:,} |"
        for k in ("as_written", "minus_clear", "minus_all")
    )
    state_rows = "\n".join(
        f"| {r.state} | {r.title_share:.0%} | {r.names_for_half:,} → "
        f"{r.names_for_half_real:,} |"
        for r in by_state.head(6).itertuples()
    )
    south_rows = "\n".join(
        f"| {r.state} | {r.title_share:.0%} | {r.names_for_half:,} → "
        f"{r.names_for_half_real:,} |"
        for r in by_state.tail(4).itertuples()
    )
    cost_rows = ""
    if cost is not None:
        cost_rows = "\n".join(
            f"| {r.token} | {r.share_of_roll:.1%} | {r.mistakes_per_100:.0f} |"
            for r in cost.head(8).itertuples()
        )

    md = f"""# Much of what looks like a surname isn't one

### And that is why a surname tells you so little

*Every number here is generated by `pipeline.py`; the tables are in `out/tab`.*

The commonest surname in India is **devi**, carried by
{lv['as_written']['top_name_share']:.1%} of the electoral roll. It is not a
surname. It is an honorific attached to a woman's name, and no family is called
Devi the way a family is called Sharma.

Nor are kumari, kaur, bai, rani, begam, khatun or bibi. Singh and Kumar are
harder: a real family name for some households and a universal title for
everyone else, with nothing in the rolls to separate the two uses.

Together these thirteen tokens sit in the surname slot for
**{lv['minus_all']['people_dropped_share']:.0%} of India** — roughly one person
in five has no family name recorded at all.

## It changes the answer to "how concentrated are Indian names?"

| counting | commonest name | names for 25% | names for half |
|---|---|---|---|
{level_rows}

Eighteen tokens cover a quarter of India. Eighteen real family names do not; it
takes {lv['minus_all']['names_for_25']}. Every concentration figure depends on a
judgment about what counts as a surname, so all three are reported here and the
list itself is in `out/tab/titles.csv` to be argued with.

![How concentrated Indian surnames are]({FIG}/concentration.png)

## The north-south gap is mostly a titles gap

| state | carries a title | names for half: as written → real |
|---|---|---|
{state_rows}

At the other end:

| state | carries a title | names for half: as written → real |
|---|---|---|
{south_rows}

![Share of each state whose surname slot holds a title]({FIG}/title_share.png)

Three people in four in Punjab have a title where a surname would go — Singh and
Kaur, given to every Sikh man and woman. In Bihar it is
{st('Bihar', 'title_share'):.0%}, mostly Devi. In Tamil Nadu it is
{st('Tamil Nadu', 'title_share'):.0%} and in Kerala
{st('Kerala', 'title_share'):.0%}.

So the story is not that northern names are concentrated and southern names are
diverse. It is that in much of the north most people do not carry a family name
on the roll at all. Drop the titles and Punjab goes from
{st('Punjab', 'names_for_half'):,} names to
{st('Punjab', 'names_for_half_real'):,}, Haryana from
{st('Haryana', 'names_for_half'):,} to
{st('Haryana', 'names_for_half_real'):,}, while Kerala barely moves.

![Names needed to cover half of each state]({FIG}/names_for_half.png)

## These are exactly the names that tell you nothing

This is where the three analyses in this repo meet. Guessing the caste of
someone you know nothing about costs {s['blind_mistakes_per_100']:.0f} mistakes
per hundred. Here is what the titles cost:

| token | share of the roll | mistakes per 100 |
|---|---|---|
{cost_rows}

Every one of the large Hindu titles lands at or worse than knowing nothing. That
is not a coincidence and it is not about caste being hidden: a token that is
given to everybody cannot distinguish anybody. The Muslim honorifics score well
only because they mark religion, and the census files Muslims under "Other".

The first analysis found that for 91% of people a surname does not change your
best guess. This is the mechanism. A fifth of the country is carrying a word that
was never meant to identify a family.

## Is the long tail just misspellings?

A reasonable suspicion, since these names are parsed from scanned rolls. It does
not survive measurement: folding every plausible variant into its common
spelling merges {v['merges']:,} names and moves
{v['people_moved'] / 1e6:.1f} million people, **{v['share_of_tokens_moved']:.1%}
of the roll**. The curve does not visibly shift.

![Names as written against names with variants folded in]({FIG}/variant_band.png)

Matching is deliberately narrow, because a loose rule is worse than none. Edit
distance alone merges `raul` into `raut`, `ari` into `ali` and `ajam` into
`alam`, which are different names rather than different spellings. Only three
kinds of edit are accepted — a vowel written as another vowel (`kamar`/`kumar`),
a doubled consonant written single (`hassan`/`hasan`), and an aspirating `h`
present or absent (`sahu`/`shahu`). The 200 largest merges are in
`out/tab/variant_merges.csv`.

## What bounds these numbers

- **The title list is a judgment.** It is published, split into the clear cases
  and the two ambiguous ones, and every figure is reported at all three levels
  so a reader can take the conservative half.
- **Titles are not the only thing in the surname slot.** Patronymics are common
  in the south, and scanned rolls carry OCR debris. Neither is quantified here,
  so {lv['minus_all']['people_dropped_share']:.0%} is a floor on how much of the
  surname column is not a family name.
- **Names appearing once or twice are absent**, and so are names shorter than
  three letters. The second matters most in the south: in Kerala's public
  service records, **{s['kerala_single_initial_share']:.0%} of candidates have a
  last token that is a single initial**, the Malayali convention of putting the
  house or father's name there as a letter. Those people are not in this data at
  all, so Kerala's {st('Kerala', 'names_for_half_real'):,} names describe only
  the Keralites who carry a spelled-out name.
- **These are electoral rolls**: adults, and transcriptions.

---

*Surname frequencies from [instate](https://github.com/appeler/instate)'s 2017
electoral-roll counts. The mistakes-per-100 column comes from
[outkast](https://github.com/appeler/outkast)'s SECC 2011 extract, the same
source as analysis 01. The Kerala initial share is computed from the name field
of the Kerala PSC records in [pranaam](https://github.com/appeler/pranaam) and
touches no caste field.*
"""
    out = HERE / "note.md"
    out.write_text(reflow(md))
    print(f"wrote {out} ({len(out.read_text().splitlines())} lines)")


if __name__ == "__main__":
    main()
