"""Render note/note.md from the generated tables.

Every number is read from out/tab, so nothing is hand-copied and the prose
cannot drift from the build.
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent

TAB = HERE / "out/tab"
FIG = "out/fig"


def pct(x: float, d: int = 0) -> str:
    return f"{x * 100:.{d}f}%"


def reflow(md: str, width: int = 80) -> str:
    """Rewrap prose and bullet lists; leave headings, tables and images alone."""

    def fill(text: str, indent: str = "") -> str:
        return textwrap.fill(
            " ".join(text.split()),
            width=width,
            initial_indent=indent,
            subsequent_indent=indent,
            break_on_hyphens=False,
            break_long_words=False,
        )

    out = []
    for block in md.split("\n\n"):
        stripped = block.strip()
        if not stripped or stripped[0] in "#|!>" or "\n|" in block:
            out.append(block)
        elif stripped.startswith("- "):
            items, current = [], []
            for line in block.split("\n"):
                if line.startswith("- ") and current:
                    items.append(" ".join(current))
                    current = [line]
                else:
                    current.append(line)
            items.append(" ".join(current))
            out.append(
                "\n".join(fill(i[2:], "  ").replace("  ", "- ", 1) for i in items)
            )
        else:
            out.append(fill(block))
    return "\n\n".join(out) + "\n"


def main() -> None:
    h = json.loads((TAB / "headline.json").read_text())
    rp = pd.read_csv(TAB / "recall_precision.csv", index_col=0)
    floors = pd.read_csv(TAB / "floor_sensitivity.csv")
    named = pd.read_parquet(TAB / "per_name_secc_weighted.parquet")
    idx = named.set_index("last_name")
    d = h["signal_decomposition"]
    cov = h.get("coverage_delhi", {})
    roll = h["weighted"]["roll"]
    base = roll["base_rates"]
    outranks = h.get("discrimination", {}).get("roll", {})
    outranks_secc = h.get("discrimination", {}).get("secc", {})

    def per100(x: float) -> str:
        """Never round a small non-zero rate down to a flat 0."""
        v = x * 100
        return "under 1" if 0 < v < 0.5 else f"{v:.0f}"

    def sc100(name: str) -> str:
        return per100(float(idx.loc[name, "p_sc"]))

    def wrong(name: str) -> str:
        return per100(float(idx.loc[name, "err"]))

    def miss(name: str) -> int:
        """Of a hundred people with this name, how many the best guess gets wrong."""
        return round(float(idx.loc[name, "err"]) * 100)

    ranked = named.sort_values("n", ascending=False)
    tail_median = round(float(ranked.iloc[10:]["err"].median()) * 100)
    top10_median = round(float(ranked.iloc[:10]["err"].median()) * 100)
    blind = round(roll["err_blind"] * 100)
    with_name = round(roll["err_per_person"] * 100)
    top10_roll_share = float(
        ranked.iloc[:10]["share_roll"].sum() / ranked["share_roll"].sum()
    )

    def rp_row(cat: str, label: str) -> str:
        r = rp.loc[cat]
        return (
            f"| {label} | {pct(r['share_of_people'])} "
            f"| {pct(r['recall'])} | {pct(r['precision'])} |"
        )

    rp_rows = "\n".join(
        rp_row(c, lab)
        for c, lab in (("SC", "Dalit"), ("ST", "Adivasi"), ("Other", "neither"))
    )

    ladder = [
        ("jha", "settles it"),
        ("yadav", "settles it"),
        ("sharma", "settles it"),
        ("chamar", "nearly settles it"),
        ("paswan", "nearly settles it"),
        ("singh", "no better than a stranger"),
        ("devi", "no better than a stranger"),
        ("kumar", "slightly worse than a stranger"),
        ("kaur", "worse than a stranger"),
        ("lal", "much worse"),
        ("ram", "much worse"),
    ]
    ladder_rows = "\n".join(f"| {n.title()} | {miss(n)} | {g} |" for n, g in ladder)

    md = f"""# On a last-name basis

### How much does an Indian surname tell you about caste?

*Draft. Every number here is generated by `scripts/build.py`; the tables are in
`out/tab`.*

You meet someone in a city big enough that you have no idea where their family
is from. All you have is a last name. How much does that narrow down their
caste — and if you had to guess, how often would you be wrong?

## Start with a room of a hundred people

Take a hundred adults at random. About {base['sc'] * 100:.0f} are Dalit
(Scheduled Caste), about {base['st'] * 100:.0f} are Adivasi (Scheduled Tribe),
and about {base['other'] * 100:.0f} are neither.

Now guess. You know nothing about anyone, so you say "neither" every time,
because that is the safest single answer. You are wrong
{roll['err_blind'] * 100:.0f} times out of a hundred.

That is the number to beat.

## First, does the name carry anything at all?

Accuracy cannot answer that. A rule naming the largest category is right 70 times
in 100 in a population that is 70% one group, whatever surnames reveal, so an
accuracy figure is mostly a statement about the base rate.

Rank people instead. Take one Dalit and one non-Dalit at random and order the
pair by what their surnames say about caste. **The Dalit ranks higher
{100 * outranks.get('sc', 0):.0f} times in 100**, and
{100 * outranks_secc.get('sc', 0):.0f} weighting people as SECC records them. For
Adivasi against everyone else it is {100 * outranks.get('st', 0):.0f}. A surname
carrying nothing would give 50.

So the name is far from silent. What follows is what happens when that
information has to become a single answer.

## Now you get to hear the name

For some names this changes everything. For most it changes nothing at all.

![A hundred people with each name]({FIG}/name_waffles.png)

Read a few of them:

- **Jha.** Fewer than 1 in 100 are Dalit. Say "neither" and you are all but
  certain to be right. This name has genuinely told you something.
- **Kumar.** {sc100('kumar')} in 100. Say "neither" and you are wrong
  {wrong('kumar')} times. You were wrong {roll['err_blind'] * 100:.0f}
  times before you heard the name. It has bought you almost nothing.
- **Ram.** {sc100('ram')} in 100 — very nearly a coin flip. Your best answer is
  still "neither", and now you are wrong {wrong('ram')} times, *worse* than the
  {roll['err_blind'] * 100:.0f} you started with. The name has not misled
  you; it has correctly told you this is a hard case.
- **Paswan.** {sc100('paswan')} in 100. Here, and only here, your answer
  actually changes: you now say "Dalit", and you are wrong {wrong('paswan')}
  times.

## The catch: almost nobody is called Paswan

Here is the thing that decides the answer. Indian surnames are enormously
concentrated, and the enormous ones are the empty ones.

![The commonest names in India tell you almost nothing]({FIG}/common_and_empty.png)

Devi, Singh and Kumar are the three commonest surnames in the country. Together
with a dozen others in the same position they are about a fifth of every
surname on India's electoral rolls — and every one of them sits within five
people-in-a-hundred of the rate for the population at large. Knowing someone is
called Kumar tells you very nearly what you already knew.

So the honest way to ask the question is not "pick a name" but "pick a person".
Pick one at random and you are far more likely to get a Devi than a Paswan.

![A hundred people picked at random]({FIG}/random_hundred.png)

Weighted that way — by who you would actually meet —
{pct(h['share_within_5pts_of_base'])} of people carry a surname that lands
within five points of the base rate, and
{pct(roll['share_guess_unchanged'])} carry one that does not change
your best guess at all.

## Why the five-mistake improvement is misleading

Across everyone, hearing names takes you from {blind} mistakes per hundred to
{with_name}. Five saved. That sounds like a modest but real gain, and the
trouble with it is that it describes nobody.

It is an average over three quite different situations. A few names settle the
question outright — Jha, Tiwari, Yadav, Sharma cost you one or two mistakes in a
hundred. Most names do nothing: for
{pct(roll['share_guess_unchanged'])} of people the name does not change the word
that comes out of your mouth, because you were going to say "neither" and you
still say "neither". And for
{pct(h['share_harder_than_stranger'])} of people the name makes the guess
*harder* than it was for a stranger.

Average a large group at zero, a large group below zero, and a small group at
almost everything, and you get five. No individual encounter looks like five.

![Mistakes using the name against mistakes ignoring it](../out/fig/err_vs_blind.png)

Every grey dot sitting on that diagonal is a name that left your answer exactly
where it already was. The big dots — the names carried by the most people — are
all on it.

## What names are good at, and what they are not

The improvement that does exist is lopsided, and the direction matters.

| | share of people | how many the guessing finds | when it does say so, how often right |
|---|---|---|---|
{rp_rows}

Names are good at ruling people **out**. Jha, Tiwari, Yadav, Sharma all put you
under two in a hundred. Ruling people **in** is much rarer: surnames find only
{pct(rp.loc['SC', 'recall'])} of Dalits, though when a name does point that way
it is right {pct(rp.loc['SC', 'precision'])} of the time.

Put plainly: {pct(1 - rp.loc['SC', 'recall'])} of Dalits carry a surname that
does not mark them. The
mistake this makes is nearly always in one direction — Dalit and Adivasi people
read as neither. The reverse barely happens.

## One number, and it is just a count

There is no need for anything fancier than the count we have been using all
along: **of a hundred people with this name, how many would you get wrong?**

A stranger — someone whose name you have not heard — costs you {blind} mistakes
per hundred. So {blind} is the number every name is competing against.

| name | mistakes per 100 | |
|---|---|---|
{ladder_rows}

Two things in that ladder are worth stopping on.

**Jha does more work than Paswan.** Paswan is the dramatic name: it is the one
that actually changes your answer, from "neither" to "Dalit". But
{miss('paswan')} in 100 Paswans are not Dalit, so you still get {miss('paswan')}
wrong. Jha costs you {miss('jha')}. Being surprised by a name and being certain
after hearing it are not the same thing, and it is certainty the question asked
about.

**Some names leave you worse off than knowing nothing.** Ram is very nearly an
even split, so hearing it costs you {miss('ram')} mistakes against the {blind}
you were already making. The name has not lied to you — it has correctly told
you this is a hard case. But it has not helped. That is not one odd name:
{pct(h['share_harder_than_stranger'])} of people carry a surname that leaves the
guess harder than a stranger's.

And the shape behind that average is the whole story. The ten commonest names
are {pct(top10_roll_share)} of everyone, and they cost a median {top10_median}
mistakes — against {blind} for a stranger. They are, as a group, no help
whatever. Past those ten almost every name does help, and by roughly the same
amount however rare it is: the median from rank eleven down to rank three
thousand is about {tail_median} mistakes. The step happens at rank ten, and the
people are all on the wrong side of it.

![Mistakes per 100, against how common the name is]({FIG}/mistakes_by_rank.png)

![Cumulative share of people by mistakes per 100]({FIG}/mistakes_cdf.png)

## Is the name really about caste, or just about region?

A fair objection. Lumping the whole country together is a way of saying "you
don't know where they're from" — and a name that merely marks a region would
pick up that region's caste mix and look informative without being about caste
at all.

It does not hold up, and the check is in the same unit as everything else. Take
a hundred people:

| what you know about them | mistakes per 100 |
|---|---|
| nothing | {d['mistakes_knowing_nothing']:.0f} |
| only which state they are from | {d['mistakes_knowing_state']:.0f} |
| only their last name | {d['mistakes_knowing_name']:.0f} |
| both | {d['mistakes_knowing_both']:.0f} |

(This table counts each record in the census once, rather than weighting by
how common a name is on the rolls, so its baseline is
{d['mistakes_knowing_nothing']:.0f} rather than the {blind} used elsewhere. The
comparison between the rows is the point, not the level.)

Knowing someone's state and nothing else buys you nothing whatever — you still
say "neither" everywhere, and you are still wrong
{d['mistakes_knowing_nothing']:.0f} times. The name does all the work, and
adding the state on top of it saves barely
{d['mistakes_knowing_name'] - d['mistakes_knowing_both']:.0f} more. Whatever the
name is telling you, it is not a map.

## What this does not cover

**There is no OBC here.** The source records three categories — Scheduled
Caste, Scheduled Tribe, and everyone else — and that third bucket is
{pct(base['other'])} of the data. So everything above is about how legible
*Dalit and Adivasi status* is. The line between backward and forward castes,
which is where a great deal of everyday caste sorting actually happens, is
invisible in this data. Yadav comes out at {sc100('yadav')} in 100, which says
"not Dalit" and says nothing whatever about the rest.

**Plenty of names are missing.** The table holds {h['names']:,} surnames from 19
states. Sood, Iyer, Balmiki and Agarwal are simply not in it. Matched against
Delhi's electoral roll it can speak to {pct(cov.get('matched_share', 0))} of
surnames on the page — and separately,
{pct(cov.get('single_token_share', 0))} of Delhi's electors are listed with a
single name and no surname at all.

**Rare names were removed, not merged, and they are the identifiable ones.**
The census extract keeps only surnames carried by more than a thousand people:
140.2M household-head records become 109.9M after cleaning and then
**93.4M**, so **15% of people are dropped for having an uncommon name**. Since
rare names identify their bearers better than common ones, the survivors are the
harder half and the figures here understate what a name gives away.

Measuring the size of that in Bihar's Mahadalit census, which has no such floor:
people whose surname has fewer than a thousand bearers cost **26.5** mistakes per
hundred against **30.4** for the rest. About four. Carried across to a censored
15%, the headline would move from 20 to roughly 19.5 -- real, in the direction
that flatters this analysis, and small.

Worth saying how that number was arrived at, because the naive version is three
times larger and wrong. Plug-in error puts the rare group at 18.1, but 40,076 of
the 50,848 rarest names in that census have a single bearer, and a name carried
by one person is "predicted" perfectly by construction. Scoring each person
against a table that excludes them removes the artefact and two-thirds of the
apparent gap with it.

**The cautious data makes names look worse, not better.** The published table
drops any cell with fewer than 100 records, and rare cells are the sharp ones.
Raising that floor makes names *less* useful, not more — from
{floors.iloc[0]['err_per_person'] * 100:.0f} mistakes per hundred at a floor of
{int(floors.iloc[0]['min_support'])} to
{floors.iloc[-1]['err_per_person'] * 100:.0f} at
{int(floors.iloc[-1]['min_support'])} — so if anything these figures flatter
surnames rather than the reverse.

**This is a perfect guesser, not a person.** It is a floor on what is knowable
from a surname, not a ceiling on what someone can work out about you. A real
person in a real city also has your first name, your father's or husband's name,
your neighbourhood, your accent. Each of those is another draw. All this says is
that *the surname on its own*, for most of the people who have one, is a much
weaker signal than its reputation.

---

*Source: [outkast](https://github.com/appeler/outkast)'s disclosure-limited
extract of the Socio-Economic and Caste Census 2011
({h['records'] / 1e6:.0f}M household-head records, adults, cells of at least
100). How common each name is comes from
[instate](https://github.com/appeler/instate)'s 2017 electoral-roll counts,
because SECC counts heads of household and so undercounts women's surnames
badly. Name–caste association drifts over time; do not read these numbers to the
decimal place.*
"""
    out = HERE / "note.md"
    out.write_text(reflow(md))
    print(f"wrote {out} ({len(out.read_text().splitlines())} lines)")


if __name__ == "__main__":
    main()
